local NeoTree = {
		NeoTreeTabInactive = {fg = C.gray, bg = C.bg, },
		NeoTreeTabActive = {fg = C.blue, bg = C.bg, },
		NeoTreeTabSeparatorInactive = {fg = C.gray, bg = C.bg, },
		NeoTreeTabSeparatorActive = {fg = C.blue, bg = C.bg, },
		NeoTreeBufferNumber = {fg = C.magenta, },
		NeoTreeCursorLine = {bg = C.base2, },
		NeoTreeDimText = {fg = C.gray, },
		NeoTreeDirectoryIcon = {fg = C.blue, },
		NeoTreeDirectoryName = {fg = C.blue, },
		NeoTreeDotfile = {fg = C.fg, },
		NeoTreeFileIcon = {fg = C.gray, },
		NeoTreeFileName = {fg = C.fg, },
		NeoTreeFileNameOpened = {fg = C.fg, },
		NeoTreeFilterTerm = {fg = C.fg, },
		NeoTreeFloatBorder = {fg = C.blue, bg = C.bg, },
		NeoTreeFloatTitle = {fg = C.blue, },
		NeoTreeTitleBar = {fg = C.blue, },
		NeoTreeGitAdded = {fg = C.tree_sign_add, },
		NeoTreeGitConflict = {fg = C.tree_sign_change, },
		NeoTreeGitDeleted = {fg = C.sign_delete, },
		NeoTreeGitIgnored = {fg = C.gray, },
		NeoTreeGitModified = {fg = C.green, },
		NeoTreeGitUnstaged = {fg = C.green, },
		NeoTreeGitUntracked = {fg = C.red, },
		NeoTreeGitStaged = {fg = C.blue, },
		NeoTreeHiddenByName = {fg = C.gray, },
		NeoTreeExpander = {fg = C.gray, },
}

return NeoTree